(() => {
  const overrides = {
    en: {
      'hero.eyebrow':'Paulownia forestry · Bulgaria · European Union',
      'hero.text':'EverRoot is a planned 70-hectare Paulownia Shan Tong forestry project in Southern Bulgaria, developed through an adaptive 10 → 30 → 30 ha rollout and focused primarily on industrial timber production.',
      'hero.deck':'Request project materials <span>↓</span>',
      'hero.note':'Current project materials available on request.',
      'snapshot.m1':'Target plantation',
      'snapshot.m2':'Trees at full scale',
      'snapshot.m3':'Planting layout',
      'snapshot.m4':'Base first-harvest assumption',
      'snapshot.note':'Current concept: 70 ha total, 43,750 trees at 4×4 m and staged development of 10 + 30 + 30 ha. Supplier pricing, site conditions, water supply and timber-market assumptions are being validated before the financing structure is finalised.',
      'project.lead':'EverRoot combines long-term land control, staged plantation development and timber production in a lean operating model.',
      'project.p1':'The current target is 70 hectares in Southern Bulgaria. Development begins with a 10-ha pilot; after validating the site, water supply and first-season operations, the plan scales through two additional 30-ha cohorts.',
      'project.f1t':'EU-based project',
      'project.f1':'Suitable land is to be secured primarily through long-term lease, with lease-and-ownership combinations possible and purchase considered only where economically justified.',
      'project.f2t':'Adaptive rollout',
      'project.f2':'A 10-ha pilot comes first. Expansion to 70 ha follows only after technical and operating conditions are validated.',
      'project.f3t':'Timber-first model',
      'project.f3':'The base commercial strategy is the sale of roundwood. Processing remains an optional future route for selected material rather than a requirement of the base case.',
      'project.f4t':'Water-led production system',
      'project.f4':'The plan uses scalable drip irrigation and, where the site supports it, a dedicated borehole or groundwater source. Final engineering remains subject to supplier and site validation.',
      'project.f5t':'Lean operating model',
      'project.f5':'The core team is planned around the founder-manager and one technician, supported by external agronomy, accounting and seasonal or contracted crews when required.',
      'model.title':'Scale is built after validation.',
      'model.text':'The operating model separates pilot validation from scale-up and is centred on plantation establishment, disciplined management and roundwood sales.',
      'model.s1t':'10 ha pilot',
      'model.s1':'The first cohort is used to validate site suitability, irrigation, planting practice, survival and the real operating workload before full-scale expansion.',
      'model.s1d':'Stage 1 · validate site, water and operations',
      'model.s2t':'First scale-up',
      'model.s2':'If the pilot passes the technical and operating gate, the current plan adds 30 ha to reach 40 ha in total.',
      'model.s2d':'Stage 2 · 40 ha cumulative',
      'model.s3t':'Full estate',
      'model.s3':'A final 30-ha cohort brings the plantation to the 70-ha target, subject to site, water, establishment and operating-cost validation.',
      'model.s3d':'Stage 3 · 70 ha target',
      'model.s4t':'Timber harvest',
      'model.s4':'The base strategy prioritises staggered sales of logs / roundwood by cohort. Processing remains an optional future route where economically justified.',
      'model.s4d':'Base planning windows · Years 7–9',
      'plant.title':'An adaptive development path.',
      'plant.text':'Planting and future harvests are organised by cohort so the project can validate the 10-ha pilot before committing the full 70 ha.',
      'roadmap.title':'Pilot first. Scale after validation.',
      'roadmap.text':'Current working strategy: 10 ha in Year 0, +30 ha in Year 1 and +30 ha in Year 2, subject to the pilot gate and confirmation of site and water conditions.',
      'roadmap.y1':'Commercial pilot',
      'roadmap.y2':'40 ha cumulative',
      'roadmap.y3':'70 ha cumulative',
      'roadmap.y4':'Management, growth and quality formation',
      'roadmap.y5':'First cohort · target window',
      'roadmap.y6':'Second cohort · target window',
      'roadmap.target':'Final cohort · target window',
      'tree.lead':'EverRoot is built around Paulownia Shan Tong, selected for fast juvenile growth, lightweight timber and the potential to regenerate from an established root system after harvest.',
      'tree.f1':'Planting density in the current model',
      'tree.f2':'Base first commercial cycle assumption',
      'tree.f3':'Vegetatively propagated hybrid planned',
      'tree.note':'Agronomic performance depends on genetics, site, irrigation, climate and management. The 7-year cycle and other production figures are planning assumptions, not guarantees.',
      'invest.title':'Interested in the current project model?',
      'invest.text':'The financing structure is being updated using live supplier quotations, site due diligence and timber-market validation. EverRoot does not present a fixed public capital requirement until those inputs are verified.',
      'invest.li1':'Plantation model and adaptive 70-ha rollout strategy defined',
      'invest.li2':'Seedling suppliers, irrigation engineering and water source under validation',
      'invest.li3':'Land selection and timber-buyer / market validation in progress',
      'invest.li4':'10-ha pilot planned; phased capital and investor structure under development',
      'form.title':'Request current project materials',
      'form.button':'Request materials <span>→</span>',
      'form.success':'Thank you. Your request has been received. We will reply with the current EverRoot project materials.',
      'form.error':'We could not send your request. Please check your details and try again.',
      'form.messageph':'Tell us briefly what you would like to review',
      'init.text':'Founder and operational lead of EverRoot, responsible for project development, financial modelling, supplier validation and coordination of the plantation strategy.',
      'contact.text':'To request the current project brief, financial model or an online project discussion, use the form above or email us.',
      'footer.disclaimer':'EverRoot is in pre-development. Project, agronomic and financial assumptions are being validated through supplier quotations, site due diligence and market research and remain subject to change.'
    },
    pl: {
      'hero.eyebrow':'Plantacja paulowni · Bułgaria · Unia Europejska',
      'hero.text':'EverRoot to planowany 70-hektarowy projekt plantacji Paulownia Shan Tong w południowej Bułgarii, rozwijany etapowo według modelu 10 → 30 → 30 ha i skoncentrowany przede wszystkim na produkcji drewna przemysłowego.',
      'hero.deck':'Poproś o materiały projektu <span>↓</span>',
      'hero.note':'Aktualne materiały projektu dostępne na życzenie.',
      'snapshot.m1':'Docelowa powierzchnia',
      'snapshot.m2':'Liczba drzew przy pełnej skali',
      'snapshot.m3':'Rozstaw sadzenia',
      'snapshot.m4':'Bazowe założenie pierwszego zbioru',
      'snapshot.note':'Obecna koncepcja: 70 ha, 43 750 drzew w rozstawie 4×4 m oraz rozwój etapami 10 + 30 + 30 ha. Ceny dostawców, warunki działki, źródło wody i założenia rynku drewna są obecnie weryfikowane przed finalizacją struktury finansowania.',
      'project.lead':'EverRoot łączy długoterminową kontrolę nad gruntem, etapowy rozwój plantacji i produkcję drewna w oszczędnym modelu operacyjnym.',
      'project.p1':'Docelowa powierzchnia wynosi obecnie 70 hektarów w południowej Bułgarii. Rozwój rozpoczyna się od pilotażu 10 ha; po weryfikacji działki, źródła wody i pierwszego sezonu plan zakłada dwa kolejne etapy po 30 ha.',
      'project.f1t':'Projekt w UE',
      'project.f1':'Odpowiedni grunt ma być zabezpieczony przede wszystkim w drodze długoterminowej dzierżawy; możliwe jest łączenie dzierżawy i własności, a zakup będzie rozważany tylko wtedy, gdy będzie ekonomicznie uzasadniony.',
      'project.f2t':'Adaptacyjne skalowanie',
      'project.f2':'Najpierw powstaje pilotaż 10 ha. Rozbudowa do 70 ha następuje dopiero po potwierdzeniu warunków technicznych i operacyjnych.',
      'project.f3t':'Model oparty na drewnie',
      'project.f3':'Podstawowa strategia handlowa zakłada sprzedaż drewna okrągłego. Przetwarzanie pozostaje opcjonalną przyszłą możliwością dla wybranej części surowca.',
      'project.f4t':'System oparty na pewnym źródle wody',
      'project.f4':'Plan zakłada skalowalne nawadnianie kroplowe oraz, jeśli działka na to pozwoli, własną studnię lub źródło wód podziemnych. Ostateczna inżynieria wymaga weryfikacji dostawców i działki.',
      'project.f5t':'Oszczędny model operacyjny',
      'project.f5':'Rdzeń zespołu ma tworzyć założyciel-kierownik i jeden technik, wspierani przez zewnętrznego agronoma, księgowość oraz sezonowe lub kontraktowe ekipy.',
      'model.title':'Skala powstaje po weryfikacji.',
      'model.text':'Model operacyjny oddziela weryfikację pilotażu od skalowania i koncentruje się na założeniu plantacji, zdyscyplinowanym zarządzaniu oraz sprzedaży drewna okrągłego.',
      'model.s1t':'Pilotaż 10 ha',
      'model.s1':'Pierwsza kohorta służy do sprawdzenia działki, nawadniania, technologii sadzenia, przeżywalności i rzeczywistego nakładu pracy przed pełnym skalowaniem.',
      'model.s1d':'Etap 1 · weryfikacja działki, wody i operacji',
      'model.s2t':'Pierwsze skalowanie',
      'model.s2':'Po pozytywnej weryfikacji technicznej i operacyjnej pilotażu plan zakłada dodanie 30 ha, do 40 ha łącznie.',
      'model.s2d':'Etap 2 · łącznie 40 ha',
      'model.s3t':'Pełna plantacja',
      'model.s3':'Ostatnia kohorta 30 ha prowadzi do docelowych 70 ha, pod warunkiem potwierdzenia działki, wody, przyjęcia sadzonek i kosztów operacyjnych.',
      'model.s3d':'Etap 3 · cel 70 ha',
      'model.s4t':'Zbiór drewna',
      'model.s4':'Strategia bazowa zakłada etapową sprzedaż kłód / drewna okrągłego według kohort. Przetwarzanie pozostaje przyszłą opcją, jeśli będzie ekonomicznie uzasadnione.',
      'model.s4d':'Bazowe okna planistyczne · Lata 7–9',
      'plant.title':'Adaptacyjna ścieżka rozwoju.',
      'plant.text':'Sadzenie i przyszłe zbiory są organizowane w kohortach, aby najpierw zweryfikować pilotaż 10 ha, a dopiero potem angażować kapitał w pełne 70 ha.',
      'roadmap.title':'Najpierw pilotaż. Potem skalowanie.',
      'roadmap.text':'Aktualna strategia robocza: 10 ha w roku 0, +30 ha w roku 1 i +30 ha w roku 2, pod warunkiem pozytywnej weryfikacji pilotażu oraz warunków działki i wody.',
      'roadmap.y1':'Pilotaż komercyjny',
      'roadmap.y2':'Łącznie 40 ha',
      'roadmap.y3':'Łącznie 70 ha',
      'roadmap.y4':'Pielęgnacja, wzrost i kształtowanie jakości',
      'roadmap.y5':'Pierwsza kohorta · okno docelowe',
      'roadmap.y6':'Druga kohorta · okno docelowe',
      'roadmap.target':'Ostatnia kohorta · okno docelowe',
      'tree.lead':'EverRoot opiera się na Paulownia Shan Tong, wybranej ze względu na szybki wzrost młodych drzew, lekkie drewno i potencjał odrastania z rozwiniętego systemu korzeniowego po zbiorze.',
      'tree.f1':'Gęstość sadzenia w aktualnym modelu',
      'tree.f2':'Bazowe założenie pierwszego cyklu komercyjnego',
      'tree.f3':'Planowana hybryda rozmnażana wegetatywnie',
      'tree.note':'Wyniki agronomiczne zależą od genetyki, działki, nawadniania, klimatu i zarządzania. Cykl 7-letni i pozostałe parametry produkcyjne są założeniami planistycznymi, a nie gwarancją.',
      'invest.title':'Chcesz poznać aktualny model projektu?',
      'invest.text':'Struktura finansowania jest aktualizowana na podstawie bieżących ofert dostawców, due diligence działki oraz weryfikacji rynku drewna. EverRoot nie publikuje stałej kwoty zapotrzebowania na kapitał, dopóki te dane nie zostaną zweryfikowane.',
      'invest.li1':'Docelowo 70 ha · adaptacyjny rozwój 10 → 30 → 30',
      'invest.li2':'Weryfikacja dostawców, nawadniania i studni w toku',
      'invest.li3':'Wybór działki i badanie rynku drewna w toku',
      'invest.li4':'Szczegółowy model finansowy i aktualne założenia dostępne na życzenie',
      'form.title':'Poproś o aktualne materiały projektu',
      'form.button':'Poproś o materiały <span>→</span>',
      'form.success':'Dziękujemy. Otrzymaliśmy Twoje zapytanie i odpowiemy, przesyłając aktualne materiały EverRoot.',
      'form.error':'Nie udało się wysłać zapytania. Sprawdź dane i spróbuj ponownie.',
      'form.messageph':'Napisz krótko, jakie materiały chcesz przejrzeć',
      'init.text':'Założyciel i lider operacyjny EverRoot, odpowiedzialny za rozwój projektu, model finansowy, weryfikację dostawców i koordynację strategii plantacji.',
      'contact.text':'Aby otrzymać aktualny opis projektu, model finansowy lub umówić rozmowę online, użyj formularza powyżej albo napisz do nas e-mail.',
      'footer.disclaimer':'EverRoot znajduje się na etapie przygotowawczym. Założenia projektowe, agronomiczne i finansowe są weryfikowane poprzez oferty dostawców, due diligence działki oraz badanie rynku i mogą ulec zmianie.'
    },
    uk: {
      'hero.eyebrow':'Плантація павловнії · Болгарія · Європейський Союз',
      'hero.text':'EverRoot — запланований 70-гектарний проєкт промислової плантації Paulownia Shan Tong у південній Болгарії, що розвивається за адаптивною схемою 10 → 30 → 30 га та орієнтований насамперед на виробництво деревини.',
      'hero.deck':'Запросити матеріали проєкту <span>↓</span>',
      'hero.note':'Актуальні матеріали проєкту доступні за запитом.',
      'snapshot.m1':'Цільова площа плантації',
      'snapshot.m2':'Кількість дерев у повному масштабі',
      'snapshot.m3':'Схема посадки',
      'snapshot.m4':'Базове припущення першої рубки',
      'snapshot.note':'Поточна концепція: 70 га, 43 750 дерев за схемою 4×4 м і поетапний розвиток 10 + 30 + 30 га. Ціни постачальників, умови ділянки, водопостачання та припущення щодо ринку деревини перевіряються до остаточного визначення структури фінансування.',
      'project.lead':'EverRoot поєднує довгостроковий контроль над землею, поетапний розвиток плантації та виробництво деревини в компактній операційній моделі.',
      'project.p1':'Поточна ціль — 70 гектарів у південній Болгарії. Розвиток починається з пілотних 10 га; після перевірки ділянки, водопостачання та першого сезону план передбачає ще дві черги по 30 га.',
      'project.f1t':'Проєкт у ЄС',
      'project.f1':'Придатну землю планується залучати насамперед через довгострокову оренду; можлива комбінація оренди та власності, а купівля розглядатиметься лише за економічної доцільності.',
      'project.f2t':'Адаптивне масштабування',
      'project.f2':'Спочатку створюється пілот на 10 га. Розширення до 70 га відбувається лише після підтвердження технічних та операційних умов.',
      'project.f3t':'Модель, орієнтована на деревину',
      'project.f3':'Базова комерційна стратегія — продаж кругляка. Переробка залишається можливою майбутньою опцією для частини сировини, а не обов’язковим елементом базового сценарію.',
      'project.f4t':'Виробнича система, прив’язана до води',
      'project.f4':'План передбачає масштабоване крапельне зрошення та, якщо ділянка дозволяє, власну свердловину або джерело підземних вод. Остаточна інженерія залежить від перевірки постачальників і ділянки.',
      'project.f5t':'Компактна операційна модель',
      'project.f5':'Основна команда планується у складі засновника-керівника та одного техніка з підтримкою зовнішнього агронома, бухгалтера та сезонних або підрядних бригад.',
      'model.title':'Масштабування — після перевірки.',
      'model.text':'Операційна модель відокремлює перевірку пілота від масштабування та зосереджується на створенні плантації, системному догляді й продажу кругляка.',
      'model.s1t':'Пілот 10 га',
      'model.s1':'Перша черга потрібна для перевірки ділянки, зрошення, технології посадки, приживлюваності та реального операційного навантаження перед масштабуванням.',
      'model.s1d':'Етап 1 · перевірка ділянки, води та операцій',
      'model.s2t':'Перше масштабування',
      'model.s2':'Після успішної технічної й операційної перевірки пілота план передбачає додавання 30 га — до 40 га загалом.',
      'model.s2d':'Етап 2 · разом 40 га',
      'model.s3t':'Повна плантація',
      'model.s3':'Остання черга 30 га доводить плантацію до цільових 70 га за умови підтвердження ділянки, води, приживлюваності й операційних витрат.',
      'model.s3d':'Етап 3 · ціль 70 га',
      'model.s4t':'Заготівля деревини',
      'model.s4':'Базова стратегія передбачає поетапний продаж колод / кругляка за чергами. Переробка залишається майбутньою опцією, якщо буде економічно доцільною.',
      'model.s4d':'Базові планові вікна · Роки 7–9',
      'plant.title':'Адаптивна траєкторія розвитку.',
      'plant.text':'Посадка та майбутні рубки організовані за чергами, щоб спочатку перевірити пілотні 10 га і лише потім залучати капітал у повні 70 га.',
      'roadmap.title':'Спочатку пілот. Потім масштабування.',
      'roadmap.text':'Поточна робоча стратегія: 10 га в році 0, +30 га в році 1 та +30 га в році 2 — за умови успішної перевірки пілота, ділянки та водопостачання.',
      'roadmap.y1':'Комерційний пілот',
      'roadmap.y2':'Разом 40 га',
      'roadmap.y3':'Разом 70 га',
      'roadmap.y4':'Догляд, ріст і формування якості',
      'roadmap.y5':'Перша черга · цільове вікно',
      'roadmap.y6':'Друга черга · цільове вікно',
      'roadmap.target':'Остання черга · цільове вікно',
      'tree.lead':'EverRoot базується на Paulownia Shan Tong, обраній через швидкий ювенільний ріст, легку деревину та потенціал відновлення від сформованої кореневої системи після рубки.',
      'tree.f1':'Щільність посадки в поточній моделі',
      'tree.f2':'Базове припущення першого комерційного циклу',
      'tree.f3':'Запланований вегетативно розмножений гібрид',
      'tree.note':'Агрономічні результати залежать від генетики, ділянки, зрошення, клімату та управління. 7-річний цикл та інші виробничі показники є плановими припущеннями, а не гарантіями.',
      'invest.title':'Хочете побачити актуальну модель проєкту?',
      'invest.text':'Структура фінансування оновлюється на основі актуальних пропозицій постачальників, перевірки ділянки та дослідження ринку деревини. EverRoot не публікує фіксовану потребу в капіталі, доки ці вхідні дані не будуть підтверджені.',
      'invest.li1':'Цільова площа: 70 га · адаптивна схема 10 → 30 → 30',
      'invest.li2':'Перевірка постачальників, зрошення та свердловини триває',
      'invest.li3':'Вибір ділянки та дослідження ринку деревини тривають',
      'invest.li4':'Детальна фінансова модель та актуальні припущення доступні за запитом',
      'form.title':'Запросити актуальні матеріали проєкту',
      'form.button':'Запросити матеріали <span>→</span>',
      'form.success':'Дякуємо. Ваш запит отримано. Ми надішлемо актуальні матеріали EverRoot у відповідь.',
      'form.error':'Не вдалося надіслати запит. Перевірте дані та спробуйте ще раз.',
      'form.messageph':'Коротко напишіть, що саме ви хотіли б переглянути',
      'init.text':'Засновник і операційний керівник EverRoot, відповідальний за розвиток проєкту, фінансове моделювання, перевірку постачальників і координацію стратегії плантації.',
      'contact.text':'Щоб отримати актуальний опис проєкту, фінансову модель або домовитися про онлайн-розмову, скористайтеся формою вище або напишіть нам.',
      'footer.disclaimer':'EverRoot перебуває на передпроєктній стадії. Проєктні, агрономічні та фінансові припущення перевіряються через пропозиції постачальників, due diligence ділянки та дослідження ринку і можуть змінюватися.'
    },
    ru: {
      'hero.eyebrow':'Плантация павловнии · Болгария · Европейский союз',
      'hero.text':'EverRoot — планируемый проект промышленной плантации Paulownia Shan Tong площадью 70 га в Южной Болгарии, развиваемый по адаптивной схеме 10 → 30 → 30 га и ориентированный прежде всего на производство древесины.',
      'hero.deck':'Запросить материалы проекта <span>↓</span>',
      'hero.note':'Актуальные материалы проекта доступны по запросу.',
      'snapshot.m1':'Целевая площадь плантации',
      'snapshot.m2':'Деревьев при полном масштабе',
      'snapshot.m3':'Схема посадки',
      'snapshot.m4':'Базовое допущение первой рубки',
      'snapshot.note':'Текущая концепция: 70 га, 43 750 деревьев по схеме 4×4 м и поэтапное развитие 10 + 30 + 30 га. Цены поставщиков, условия участка, водоснабжение и предпосылки рынка древесины сейчас проверяются до окончательного определения структуры финансирования.',
      'project.lead':'EverRoot объединяет долгосрочный контроль над землёй, поэтапное развитие плантации и производство древесины в компактной операционной модели.',
      'project.p1':'Текущая цель — 70 гектаров в Южной Болгарии. Развитие начинается с пилотных 10 га; после проверки участка, источника воды и первого сезона план предусматривает ещё две очереди по 30 га.',
      'project.f1t':'Проект в ЕС',
      'project.f1':'Подходящую землю планируется привлекать прежде всего через долгосрочную аренду; возможна комбинация аренды и собственности, а покупка рассматривается только при экономической целесообразности.',
      'project.f2t':'Адаптивное масштабирование',
      'project.f2':'Сначала создаётся пилот на 10 га. Расширение до 70 га происходит только после подтверждения технических и операционных условий.',
      'project.f3t':'Модель с фокусом на древесину',
      'project.f3':'Базовая коммерческая стратегия — продажа кругляка. Переработка остаётся возможной будущей опцией для части сырья, а не обязательным элементом базового сценария.',
      'project.f4t':'Производственная система с фокусом на воду',
      'project.f4':'План предусматривает масштабируемый капельный полив и, если участок позволяет, собственную скважину или источник грунтовых вод. Окончательная инженерия зависит от проверки поставщиков и участка.',
      'project.f5t':'Компактная операционная модель',
      'project.f5':'Основная команда планируется из основателя-менеджера и одного техника с поддержкой внешнего агронома, бухгалтера и сезонных либо подрядных бригад.',
      'model.title':'Масштабирование — после проверки.',
      'model.text':'Операционная модель разделяет проверку пилота и масштабирование и сосредоточена на создании плантации, системном уходе и продаже кругляка.',
      'model.s1t':'Пилот 10 га',
      'model.s1':'Первая очередь нужна для проверки участка, полива, технологии посадки, приживаемости и реальной операционной нагрузки до полномасштабного расширения.',
      'model.s1d':'Этап 1 · проверка участка, воды и операций',
      'model.s2t':'Первое масштабирование',
      'model.s2':'После успешной технической и операционной проверки пилота план предусматривает добавление 30 га — до 40 га в сумме.',
      'model.s2d':'Этап 2 · всего 40 га',
      'model.s3t':'Полная плантация',
      'model.s3':'Последняя очередь 30 га доводит плантацию до целевых 70 га при условии подтверждения участка, воды, приживаемости и операционных затрат.',
      'model.s3d':'Этап 3 · цель 70 га',
      'model.s4t':'Заготовка древесины',
      'model.s4':'Базовая стратегия предполагает поэтапную продажу брёвен / кругляка по очередям. Переработка остаётся будущей опцией, если будет экономически оправдана.',
      'model.s4d':'Базовые плановые окна · Годы 7–9',
      'plant.title':'Адаптивный путь развития.',
      'plant.text':'Посадка и будущие рубки организованы по очередям, чтобы сначала проверить пилотные 10 га и только затем вкладывать капитал в полные 70 га.',
      'roadmap.title':'Сначала пилот. Затем масштабирование.',
      'roadmap.text':'Текущая рабочая стратегия: 10 га в год 0, +30 га в год 1 и +30 га в год 2 — при условии успешной проверки пилота, участка и водоснабжения.',
      'roadmap.y1':'Коммерческий пилот',
      'roadmap.y2':'Всего 40 га',
      'roadmap.y3':'Всего 70 га',
      'roadmap.y4':'Уход, рост и формирование качества',
      'roadmap.y5':'Первая очередь · целевое окно',
      'roadmap.y6':'Вторая очередь · целевое окно',
      'roadmap.target':'Последняя очередь · целевое окно',
      'tree.lead':'EverRoot строится вокруг Paulownia Shan Tong, выбранной за быстрый ювенильный рост, лёгкую древесину и потенциал восстановления от сформированной корневой системы после рубки.',
      'tree.f1':'Плотность посадки в текущей модели',
      'tree.f2':'Базовое допущение первого коммерческого цикла',
      'tree.f3':'Планируемый вегетативно размноженный гибрид',
      'tree.note':'Агрономические результаты зависят от генетики, участка, полива, климата и управления. 7-летний цикл и другие производственные показатели являются плановыми предположениями, а не гарантиями.',
      'invest.title':'Хотите увидеть актуальную модель проекта?',
      'invest.text':'Структура финансирования обновляется на основе актуальных предложений поставщиков, проверки участка и исследования рынка древесины. EverRoot не публикует фиксированную потребность в капитале, пока эти исходные данные не подтверждены.',
      'invest.li1':'Целевая площадь: 70 га · адаптивная схема 10 → 30 → 30',
      'invest.li2':'Проверка поставщиков, полива и скважины продолжается',
      'invest.li3':'Выбор участка и исследование рынка древесины продолжаются',
      'invest.li4':'Подробная финансовая модель и актуальные допущения доступны по запросу',
      'form.title':'Запросить актуальные материалы проекта',
      'form.button':'Запросить материалы <span>→</span>',
      'form.success':'Спасибо. Ваш запрос получен. Мы ответим и отправим актуальные материалы EverRoot.',
      'form.error':'Не удалось отправить запрос. Проверьте данные и попробуйте снова.',
      'form.messageph':'Кратко напишите, что именно вы хотели бы посмотреть',
      'init.text':'Основатель и операционный руководитель EverRoot, отвечающий за развитие проекта, финансовую модель, проверку поставщиков и координацию стратегии плантации.',
      'contact.text':'Чтобы получить актуальное описание проекта, финансовую модель или договориться об онлайн-разговоре, используйте форму выше или напишите нам.',
      'footer.disclaimer':'EverRoot находится на предпроектной стадии. Проектные, агрономические и финансовые допущения проверяются через предложения поставщиков, due diligence участка и исследование рынка и могут изменяться.'
    }
  };

  Object.entries(overrides).forEach(([lang, values]) => {
    if (!translations[lang]) translations[lang] = {};
    Object.assign(translations[lang], values);
  });

  const metricValues = ['70 ha', '43,750', '4×4 m', '7 yrs'];
  document.querySelectorAll('.metric-grid .metric strong').forEach((el, index) => {
    if (metricValues[index]) el.textContent = metricValues[index];
  });

  const roadmapValues = ['10 ha', '+30 ha', '+30 ha', '70 ha', '10 ha', '30 ha', '30 ha'];
  document.querySelectorAll('.roadmap > div > span').forEach((el, index) => {
    if (roadmapValues[index]) el.textContent = roadmapValues[index];
  });

  const stageIcons = ['🌱', '↗', '🌳', '↻'];
  document.querySelectorAll('.stage-icon').forEach((el, index) => {
    if (stageIcons[index]) el.textContent = stageIcons[index];
  });

  const treeValues = ['625/ha', '7 yrs', 'Shan Tong'];
  document.querySelectorAll('.tree-facts strong').forEach((el, index) => {
    if (treeValues[index]) el.textContent = treeValues[index];
  });

  const description = document.querySelector('meta[name="description"]');
  if (description) description.setAttribute('content', 'EverRoot — planned 70 ha Paulownia Shan Tong forestry project in Southern Bulgaria, developed through an adaptive 10 → 30 → 30 ha rollout.');

  setLang(document.documentElement.lang || localStorage.getItem('everroot-lang') || 'en');
})();

