const translations = {
  en:{
    'nav.project':'Project','nav.model':'Business model','nav.investment':'Investment','nav.initiator':'Initiator','nav.contact':'Contact','nav.cta':'Investment opportunity',
    'hero.eyebrow':'Sustainable agroforestry · European Union','hero.title':'Growing forests.<br><em>Building long-term value.</em>','hero.text':'EverRoot is an agroforestry investment project focused on sustainable Paulownia cultivation, diversified early cash flows and high-value timber production in Southern Bulgaria.','hero.explore':'Explore the project <span>↗</span>','hero.deck':'Get the investment deck <span>↓</span>','hero.note':'Investment materials available on request.',
    'snapshot.title':'A real asset with a<br>long-term growth cycle.','snapshot.m1':'Target investment','snapshot.m2':'Planned plantation','snapshot.m3':'First industrial harvest','snapshot.m4':'Long-term profit split*','snapshot.note':'*Indicative project terms shown on the current project concept. Final terms are subject to due diligence and definitive agreements.',
    'project.title':'Forestry designed as an investment asset.','project.lead':'EverRoot combines land, fast-growing forestry and downstream processing into a single long-term agricultural asset.','project.p1':'The initial concept is a 35-hectare Paulownia plantation in Southern Bulgaria, developed progressively rather than planted all at once. This creates a staged operating model and allows the project to build capacity over time.','project.f1t':'EU-based asset','project.f1':'Land and operations planned within the European Union.','project.f2t':'Regenerative cycle','project.f2':'Paulownia can regenerate from the established root system after harvest, supporting subsequent production cycles.','project.f3t':'Diversified revenue','project.f3':'Intercropping, beekeeping and timber create different economic phases.',
    'model.title':'Value is built in stages.','model.text':'The plantation is designed to generate supporting agricultural income before the main timber harvest, while the long-term value comes from premium wood and processing.','model.s1t':'Intercropping','model.s1':'Lucerne and other suitable crops between young trees during the early plantation years.','model.s1d':'Indicative phase · Years 1–3','model.s2t':'Apiculture','model.s2':'Honey production can complement the plantation as flowering develops.','model.s2d':'Indicative phase · Years 3–6','model.s3t':'Timber','model.s3':'Industrial harvest followed by drying, processing and higher-value timber products.','model.s3d':'Indicative phase · From Year 7','model.s4t':'Processing','model.s4':'A future processing layer can capture more value than selling raw logs alone.','model.s4d':'Development opportunity',
    'plant.title':'A six-year development path.','plant.text':'A staged planting program is designed to distribute establishment work, capital needs and future harvests across the development cycle.','roadmap.title':'From first hectare to full estate.','roadmap.text':'The current concept is based on approximately 5 hectares of new planting per year until the target area is established.',
    'tree.title':'A fast-growing tree with a valuable timber profile.','tree.lead':'EverRoot is built around Paulownia cultivation, selected for the combination of growth rate, lightweight timber and regenerative potential.','tree.f1':'Indicative annual growth under suitable conditions','tree.f2':'Target first commercial cycle in the current concept','tree.f3':'Hybrid under consideration for the plantation model','tree.note':'Agronomic performance depends on genetics, site, irrigation, climate and management. Figures are project assumptions, not guarantees.',
    'invest.title':'Interested in the full picture?','invest.text':'Request the investment presentation for the detailed project model, capital allocation, operating assumptions, development roadmap and partnership structure.','invest.li1':'Detailed project economics','invest.li2':'Capital requirements and use of funds','invest.li3':'Development and operating roadmap','invest.li4':'Partnership and governance concept',
    'form.title':'Request investment materials','form.name':'Full name','form.email':'Email','form.company':'Company / fund','form.message':'Message','form.button':'Request access <span>→</span>','form.note':'By submitting, you agree to be contacted regarding EverRoot. This form is a front-end demo until an email service is connected.',
    'init.title':"Built with an operator's mindset.",'init.role':'Founder & Project Initiator','init.text':'Founder and operational lead of the EverRoot project, responsible for project development, investor communication and coordination of the plantation strategy.','init.link':'Start a conversation →','contact.title':"Let's discuss the opportunity.",'contact.text':'For the full business plan, financial model or an online project presentation, get in touch directly.','footer.disclaimer':'Investment information is indicative and subject to due diligence.'
  },
  ru:{
    'nav.project':'Проект','nav.model':'Бизнес-модель','nav.investment':'Инвестиции','nav.initiator':'Инициатор','nav.contact':'Контакты','nav.cta':'Инвестиционная возможность',
    'hero.eyebrow':'Устойчивое агролесоводство · Европейский союз','hero.title':'Выращиваем леса.<br><em>Создаём долгосрочную ценность.</em>','hero.text':'EverRoot — инвестиционный агролесоводческий проект, ориентированный на устойчивое выращивание павловнии, диверсифицированные денежные потоки на ранних этапах и производство ценной древесины в Южной Болгарии.','hero.explore':'Подробнее о проекте <span>↗</span>','hero.deck':'Получить инвестиционную презентацию <span>↓</span>','hero.note':'Инвестиционные материалы доступны по запросу.',
    'snapshot.title':'Реальный актив с<br>долгосрочным циклом роста.','snapshot.m1':'Целевой объём инвестиций','snapshot.m2':'Планируемая площадь плантации','snapshot.m3':'Первая промышленная заготовка','snapshot.m4':'Распределение долгосрочной прибыли*','snapshot.note':'*Указаны ориентировочные условия текущей концепции проекта. Окончательные условия определяются после комплексной проверки и заключения окончательных соглашений.',
    'project.title':'Лесное хозяйство как инвестиционный актив.','project.lead':'EverRoot объединяет землю, быстрорастущее лесное хозяйство и переработку в единый долгосрочный сельскохозяйственный актив.','project.p1':'Первоначальная концепция предусматривает создание 35-гектарной плантации павловнии в Южной Болгарии, развиваемой поэтапно, а не высаживаемой за один раз. Такой подход формирует поэтапную операционную модель и позволяет постепенно наращивать мощности проекта.','project.f1t':'Актив в ЕС','project.f1':'Земля и операционная деятельность планируются в пределах Европейского союза.','project.f2t':'Возобновляемый цикл','project.f2':'После заготовки павловния способна восстанавливаться из сформированной корневой системы, обеспечивая последующие производственные циклы.','project.f3t':'Диверсифицированная выручка','project.f3':'Совместное выращивание культур, пчеловодство и древесина формируют разные экономические этапы.',
    'model.title':'Ценность создаётся поэтапно.','model.text':'Плантация рассчитана на получение дополнительного сельскохозяйственного дохода до основной заготовки древесины, а долгосрочная ценность формируется за счёт премиальной древесины и её переработки.','model.s1t':'Совместное выращивание культур','model.s1':'Люцерна и другие подходящие культуры между молодыми деревьями в первые годы развития плантации.','model.s1d':'Ориентировочный этап · 1–3 годы','model.s2t':'Пчеловодство','model.s2':'По мере цветения плантации производство мёда может стать дополнительным источником дохода.','model.s2d':'Ориентировочный этап · 3–6 годы','model.s3t':'Древесина','model.s3':'Промышленная заготовка с последующей сушкой, переработкой и производством продукции с более высокой добавленной стоимостью.','model.s3d':'Ориентировочный этап · с 7-го года','model.s4t':'Переработка','model.s4':'Будущие перерабатывающие мощности позволят получать больше ценности, чем продажа необработанных брёвен.','model.s4d':'Возможность для развития',
    'plant.title':'Шестилетний путь развития.','plant.text':'Поэтапная программа посадки распределяет работы по созданию плантации, потребности в капитале и будущие заготовки по всему циклу развития.','roadmap.title':'От первого гектара до полноценного лесного хозяйства.','roadmap.text':'Текущая концепция предусматривает высадку примерно 5 новых гектаров в год до достижения целевой площади.',
    'tree.title':'Быстрорастущее дерево с ценной древесиной.','tree.lead':'В основе EverRoot — выращивание павловнии, выбранной благодаря сочетанию быстрого роста, лёгкой древесины и способности к восстановлению.','tree.f1':'Ориентировочный годовой прирост при подходящих условиях','tree.f2':'Целевой срок первого коммерческого цикла в текущей концепции','tree.f3':'Гибрид, рассматриваемый для модели плантации','tree.note':'Агрономические показатели зависят от генетики, участка, орошения, климата и управления. Приведённые значения являются проектными предположениями, а не гарантиями.',
    'invest.title':'Хотите увидеть полную картину?','invest.text':'Запросите инвестиционную презентацию с подробной моделью проекта, распределением капитала, операционными предположениями, дорожной картой развития и структурой партнёрства.','invest.li1':'Подробная экономика проекта','invest.li2':'Потребность в капитале и его использование','invest.li3':'Дорожная карта развития и операционной деятельности','invest.li4':'Концепция партнёрства и управления',
    'form.title':'Запросить инвестиционные материалы','form.name':'Полное имя','form.email':'Электронная почта','form.company':'Компания / фонд','form.message':'Сообщение','form.button':'Запросить доступ <span>→</span>','form.note':'Отправляя форму, вы соглашаетесь на связь по вопросам EverRoot. До подключения почтового сервиса форма работает в демонстрационном режиме.','form.success':'Спасибо. Ваш запрос принят. Подключите почтовый сервис для автоматической отправки презентации.',
    'init.title':'Создано с мышлением практика.','init.role':'Основатель и инициатор проекта','init.text':'Основатель и операционный руководитель проекта EverRoot, отвечающий за развитие проекта, коммуникацию с инвесторами и координацию стратегии плантации.','init.link':'Начать разговор →','contact.title':'Давайте обсудим возможности.','contact.text':'Чтобы получить полный бизнес-план, финансовую модель или онлайн-презентацию проекта, свяжитесь с нами напрямую.','footer.disclaimer':'Инвестиционная информация носит ориентировочный характер и подлежит комплексной проверке.'
  }
};
const base=translations.en; ['pl','uk'].forEach(k=>translations[k]=base);
const langButtons=document.querySelectorAll('.lang');
function setLang(lang){document.documentElement.lang=lang;document.querySelectorAll('[data-i18n]').forEach(el=>{const key=el.dataset.i18n; if(translations[lang]?.[key]) el.innerHTML=translations[lang][key];});langButtons.forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));localStorage.setItem('everroot-lang',lang)}
langButtons.forEach(b=>b.addEventListener('click',()=>setLang(b.dataset.lang)));
setLang(localStorage.getItem('everroot-lang')||'en');


document.getElementById('accessForm').addEventListener('submit',e=>{e.preventDefault();const status=document.getElementById('formStatus');status.textContent=translations[document.documentElement.lang]?.['form.success'] || 'Thank you. Your request has been captured. Connect an email service to send the deck automatically.';});
const menu=document.querySelector('.menu-toggle');menu?.addEventListener('click',()=>document.querySelector('.nav').classList.toggle('mobile-open'));

